### ISSUE TITLE
Entity Relationship Diagram Design

### ISSUE THREAD

**Issue by RgieCrl** [blackMisay/Janmos#1]
**Relationships:**

**Products**
- Can belong to one Category (Optional).
- Included in many Sales.
- Included in many CustomerOrderDetails.
- Included in many SupplierOrderDetails.

**Customers**
- Make many Sales.

**Sales**
- Linked to one Product.
- Linked to one Customer.

**Suppliers**
- Have many SupplierOrders.

**Customers**
- Have many CustomerOrders.

**SupplierOrders**
- Belongs to one Supplier.
- Have many SupplierOrderDetails.

**CustomerOrders**
- Belongs to one Customer.
- Have many CustomerOrderDetails.

**SupplierOrdersDetails**
- Belongs to one SupplierOrder.
- Linked to one Product.

**CustomerOrdersDetails**
- Belongs to one CustomerOrder.
- Linked to one Product.

**Comment by blackMisay** [comment]
[Entity-Relationship-Diagram](https://drive.google.com/file/d/1kzMvFtPX1MB-0UnMq6ElTLuTPHQcPWrV/view?usp=sharing)

**Comment by RgieCrl** [comment]
[https://drive.google.com/file/d/15kMWGKWO2kY9clZRuyAWByUm0LVaRA18/view?usp=sharing](url)

**Comment by RgieCrl** [comment]
[https://drive.google.com/file/d/15kMWGKWO2kY9clZRuyAWByUm0LVaRA18/view?usp=sharing](url)

**Comment by RgieCrl** [comment]
![erd (1) drawio](https://github.com/blackMisay/Janmos/assets/150538093/702274b3-a430-44b9-a56c-50d430bcffb7)

**Comment by blackMisay** [comment]
I'm good with the changes, thanks
