### ISSUE TITLE
Update Entity Relationship Diagram

### ISSUE THREAD

**Issue by RgieCrl** [blackMisay/Janmos#13]
Customer Table
- add address (Region, Municipality, Baranggay, House Num, and Postal Code)

Create User Table
- add id auto_increment not null
- add username
- add password
- add key

**Comment by AkoToSiPat** [comment]
![image](https://github.com/blackMisay/Janmos/assets/159512324/adecc6f6-817b-4dcb-82b6-2400576e19e7)
//dinagdagan ko lang yung sa customer tapos gumawa ako ng table ng user table kaso diko pa nakokonek

**Comment by AkoToSiPat** [comment]
![image](https://github.com/blackMisay/Janmos/assets/159512324/bd6b6228-2b79-4d6e-9a5d-43be4160616d)
// nag add lang ako sa table ng customer diko alam kung ganon ba or panibagong table, kaso diko pa nakokonek tapos gumawa ng user table yung list naka drop down lang yun pero tanggalin ko nalang kung mali

**Comment by RgieCrl** [comment]
> ![image](https://private-user-images.githubusercontent.com/159512324/310546066-bd6b6228-2b79-4d6e-9a5d-43be4160616d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjAyODQsIm5iZiI6MTcwOTg1OTk4NCwicGF0aCI6Ii8xNTk1MTIzMjQvMzEwNTQ2MDY2LWJkNmI2MjI4LTJiNzktNGQ2ZS05YTVkLTQzYmU0MTYwNjE2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwMTA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTk4YzhhMzBkYzBkOWYxZTIwYmI2NjMxM2M4MmYzZmUxNWJiMmZiN2M5Y2FhZmQ1NTQ1OThlMTRmNzA2YjU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ii3el1bw-oOJ3Mq1ZWuoK3Mux5e7H9jyr00coLQa0U4) // nag add lang ako sa table ng customer diko alam kung ganon ba or panibagong table, kaso diko pa nakokonek tapos gumawa ng user table yung list naka drop down lang yun pero tanggalin ko nalang kung mali

Customer Table
- Remove the Address
- Remove the List

**Comment by AkoToSiPat** [comment]
![image](https://github.com/blackMisay/Janmos/assets/159512324/3b691d13-93b6-4ab1-b094-efebe3749c39)
// na remove ko na yung connection nalang ng user table diko pa kinokonek

**Comment by blackMisay** [comment]
@AkoToSiPat kindly attached the link wherein the ERD file is uploaded. File should be in .drawio and image format

**Comment by RgieCrl** [comment]
put into folder
- png
- editable file .io

**Comment by AkoToSiPat** [comment]
https://drive.google.com/drive/folders/1PTDd3dwz_TnbroKc9C2K7ARfEG16KDgt?usp=drive_link

**Comment by blackMisay** [comment]
@AkoToSiPat, CustomerOrder.Customer should be linked to Customer.Id, not in Customer.PrimaryEmail

![Image](https://github.com/blackMisay/Janmos/assets/39677820/c39f4ac4-2df4-402b-bfe8-fe87bd372f99)

**NOTE**: Only attached your changes here in the ticket, **DO NOT** upload the changes in GDrive unless this issue is completed. Thanks

**Comment by AkoToSiPat** [comment]
https://drive.google.com/drive/folders/1SUO1eFUBTIqfIxI9yb8_G2QJdau2PB4K?usp=sharing
//UPDATED

**Comment by RgieCrl** [comment]
@AkoToSiPat **CustomerOrder.Customer** should be linked to **Customer.Id**, not in **UserTable.id**

![Image](https://github.com/blackMisay/Janmos/assets/150538093/4124503a-b4d8-4e7f-85da-b821762eea4f)

**NOTE:** Please the understand and read the comment.

Problem:
- Connect the **CustomerOrder.Customer** to **Customer,id** not in **UserTable.id**.
- Use an appropriate relation line from **CustomerOrder.Customer** to **Customer,id**.
- The Customer Table is connected to Customer Order Table as "ONE IS TO MANY".
- The Sample of relation line is below:



![Image](https://github.com/blackMisay/Janmos/assets/150538093/bd94edb0-241b-4ba1-bb15-706623672bd4)



Additionally:
- In Product Table, add another column for Metric Unit, Metric Value and Status.

**NOTE:** 
- Do not save the changes directly to the **GDRIVE**, wait for the further announcement.
- Just post png type when your done in changes

**Comment by AkoToSiPat** [comment]
@
![ERDupdate](https://github.com/blackMisay/Janmos/assets/159512324/a5ff165f-9435-4e39-843c-a75e7db4648c)
//updated connection 
//adding metric etc.

**Comment by RgieCrl** [comment]
There is no problem in recent changes

**Addition to the ERD:**

Metric Unit Table
- add new table name "**Metric Unit**" with columns (id, symbol, name, category)
- the "metric unit" in the "Product Table" will be change as "foreign key" (FK).
- connect the "metric unit" from the "Product Table" to the "id" of "Metric Unit Table".

Metric Unit Category Table
- add new table name "**Metric Unit Category**" with columns (id, description)
- the "category" in the "Metric Unit Table" will be change as "foreign key" (FK).
- connect the "category" from the "Metric Unit Table" to the "id" of "Metric Unit Category Table".

Note: 
- The id's of both table should be "Primary Key".
- The relation of Metric Unit Table and Metric Unit Category Table should be one is to many.
- "**metricunitcategory.id**" as "one" and the "**metricunit.category**" as "many".
- The relation of Product Table and Metric Unit Table should be one is to many.
- "**metricunit.id**" as "one" and the "**product.metricunit**" as "many".

**Comment by AkoToSiPat** [comment]
![ERDmetrictables](https://github.com/blackMisay/Janmos/assets/159512324/e916d01d-9066-4a42-9abf-353e06f93822)
ADD tables for
//metric unit and metric unit category tables and its entity relation connection

**Comment by blackMisay** [comment]
**DCO_DG_ERD** for March 2024 changes are completed.
See reference: https://drive.google.com/drive/folders/1SUO1eFUBTIqfIxI9yb8_G2QJdau2PB4K?usp=sharing

![DCO_DG_ERD_2024 4](https://github.com/blackMisay/Janmos/assets/39677820/f5fedd0c-6a19-42e2-bb85-fd8a457cabd8)
