### ISSUE TITLE
[DIAGRAM] Create Software Architecture diagram 2024.4

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/Janmos#35]
This ticket will track the creation of software architecture for Chapter 3 technical background

**Comment by AkoToSiPat** [comment]
![SAD drawio](https://github.com/blackMisay/Janmos/assets/159512324/089b8e7c-1828-4077-8f4c-12edbef1e382)
//pacheck lang muna sir

**Comment by blackMisay** [comment]
@AkoToSiPat Please refrain from inputting multiple admin users into the architecture. One user should be sufficient. This diagram pertains to the architecture, not the system module or user specification module.

**Comment by AkoToSiPat** [comment]
![SAD drawio](https://github.com/blackMisay/Janmos/assets/159512324/1fbcb1c3-4278-4d60-ad66-1aa8c1f7bb41)

**Comment by blackMisay** [comment]
I'm good with the changes thanks.
Uploaded here: [DCO_DG_SWARCH_2024.04](https://drive.google.com/file/d/1p5AujCVgKrh0G1yUl5WyWLvmUUMiUOui/view?usp=drive_link)
