### ISSUE TITLE
Supplier Module Functionalities

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/Janmos#37]
Implement crud functionalities in Supplier module

**Comment by RgieCrl** [comment]
Supplier Module Functionalities including:
- supplier crud (add, edit, delete)
- new supplier data (default status value '1')
- edit supplier data
- soft deleting supplier data (update status value '0')
- filter data
- field validation in supplier modal
- populating address (region, province, municipality, baranggay)

**Comment by RgieCrl** [comment]
link for updated database in JSAI37
Supplier Functionalities


[dbjanmos.zip](https://github.com/blackMisay/Janmos/files/14810134/dbjanmos.zip)

**Comment by blackMisay** [comment]
This task did not reach completion before the deadline. I will move this ticket to the **2024.04.2** Sprint.
