### ISSUE TITLE
Review of Methodology

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/Janmos#48]
Research about Agile and Scrum Methodology

**Comment by AkoToSiPat** [comment]
https://arxiv.org/ftp/arxiv/papers/1902/1902.01821.pdf

https://iopscience.iop.org/article/10.1088/1757-899X/981/2/022060/pdf

https://sci-hub.se/https://ieeexplore.ieee.org/document/5233355

**Comment by blackMisay** [comment]
I'm good, make use of this research as reference in creating Methodology in Chapter 3.
Uploaded here: [DCO_KB](https://drive.google.com/drive/folders/1VWf7PCjHKsWvjM0z-Z_sezHVvi0x-DGJ?usp=drive_link)
